#!/bin/bash

# configure db user
USER='divvystat'
PASS=''

# check first and second params for dates (YYYY-MM-DD)
if [ -z $1 ]
then
    echo 'provide first param as start date (ie 2014-02-01)'
    exit 0
fi
if [ -z $2 ]
then
    echo 'provide second param as end date + 1 (ie 2014-03-01 for feb)'
    exit 0
fi

# perform query to csv
echo "select * from outages where timestamp between \"${1}\" and \"${2}\" order by timestamp asc" \
    | mysql -u ${USER} -p${PASS} divvystat \
    | sed 's/\t/,/g' > outages_${1}.csv
