version: '3'

services:

  redis:
    image: redis:latest

  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: divvystat
      MYSQL_PASSWORD: divvystat
      MYSQL_DATABASE: divvystat

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    command: /code/docker/php/start.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mysql
