version: '3.7'

services:

  redis:
    image: redis:latest

  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: divvystat
      MYSQL_PASSWORD: divvystat
      MYSQL_DATABASE: divvystat

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    command: /code/docker/php/start.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mysql

  divvystat-postgres-local:
    restart: always
    image: postgres:11
    env_file:
      - .env
    volumes:
      - ./docker/local/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

