#!/bin/bash

# configure db user
USER=''
PASS=''

# configure prod and dev dbs
PROD=''
DEV=''

# get timestamp
TS=$( date +%s )

# perform
mysqldump --opt -u ${USER} -pVexVatinn ${PROD}  > database_dump_${TS}.sql
echo "drop database ${DEV}" | mysql -u ${USER} -pVexVatinn
echo "create database ${DEV}" | mysql -u ${USER} -pVexVatinn
mysql -u ${USER} -pVexVatinn ${DEV} < database_dump_${TS}.sql

