#!/bin/sh

# use the psql command line tool to access the postgres docker container

# values from the .env file

docker-compose exec divvystat-postgres-local sh -c 'export PGPASSWORD=$POSTGRES_PASSWORD ; psql -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_DB'
